# Generated by run_ablation.py for variant: 01_current_all_features
"""Prosperity 4 Round 4 trader (v2 — robust hybrid).

Improvements over v1:
- Per-tick reservation accounting (Book) is the single source of capacity.
- Two-pass S_hat estimation with anchor rejection and prev-S_hat fallback.
- VEV residual z-scores (compact EWMA) used as a tilt + cheap-VEV hard short rule.
- Quality-filtered, slower TV updates for ATM strikes.
- Volatility/spread-adaptive take and make edges.
- Adverse-selection filter using last_return / |flow|.
- VELVET-only paired hedge pressure separate from per-product delta skew.
- Inventory-aware maker sizing; no blind one-tick improve.
- Lightweight diagnostics counters in traderData.
- Feature flags for clean ablation.

Runtime depends only on the prosperity datamodel.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional, Tuple

from datamodel import Order, OrderDepth, Trade, TradingState


# =========================================================================== #
# Feature flags                                                                #
# =========================================================================== #

ENABLE_VEV_LADDER = True
ENABLE_DELTA_CONTROL = True
ENABLE_FLOW = True
ENABLE_RESIDUAL_Z = True
ENABLE_MR = True
ENABLE_CHEAP_VEV_RULE = True
ENABLE_ENDGAME = True
ENABLE_ADVERSE_SELECTION_FILTER = True
ENABLE_DYNAMIC_EDGES = True
ENABLE_VELVET_HEDGE_PRESSURE = True
ENABLE_TAKER = True
ENABLE_MAKER = True
SIMPLE_S_HAT = False
ACTIVE_PRODUCTS = None
TAKE_EDGE_MULT = 1.0
MAKE_EDGE_MULT = 1.0
CHEAP_SHORT_THRESHOLD_MULT = 1.5


# =========================================================================== #
# Static config                                                                #
# =========================================================================== #

LIMITS: Dict[str, int] = {
    "HYDROGEL_PACK": 32,
    "VELVETFRUIT_EXTRACT": 32,
    "VEV_4000": 20, "VEV_4500": 20, "VEV_5000": 20, "VEV_5100": 20,
    "VEV_5200": 20, "VEV_5300": 20, "VEV_5400": 20, "VEV_5500": 20,
    "VEV_6000": 20, "VEV_6500": 20,
}

STRIKES: List[int] = [4000, 4500, 5000, 5100, 5200, 5300, 5400, 5500, 6000, 6500]
VEV_BY_STRIKE: Dict[int, str] = {K: f"VEV_{K}" for K in STRIKES}
PRODUCT_TO_STRIKE: Dict[str, int] = {v: k for k, v in VEV_BY_STRIKE.items()}

WINGS = {"VEV_6000", "VEV_6500"}
CHEAP_VEVS_NON_WING = {"VEV_5400", "VEV_5500"}
CHEAP_VEVS = CHEAP_VEVS_NON_WING | WINGS
NEAR_ATM = {"VEV_5000", "VEV_5100", "VEV_5200", "VEV_5300"}

TV_SEED: Dict[int, float] = {
    4000: 0.0, 4500: 0.0, 5000: 2.75, 5100: 11.5, 5200: 39.0,
    5300: 34.0, 5400: 9.0, 5500: 2.7, 6000: 0.5, 6500: 0.5,
}
TV_BOUNDS: Dict[int, Tuple[float, float]] = {
    4000: (0.0, 2.0), 4500: (0.0, 2.0), 5000: (0.0, 8.0),
    5100: (5.0, 22.0), 5200: (25.0, 55.0), 5300: (20.0, 55.0),
    5400: (3.0, 18.0), 5500: (0.5, 9.0),
    6000: (0.5, 0.5), 6500: (0.5, 0.5),
}
DELTA: Dict[int, float] = {
    4000: 0.74, 4500: 0.67, 5000: 0.66, 5100: 0.59, 5200: 0.44,
    5300: 0.25, 5400: 0.10, 5500: 0.04, 6000: 0.0, 6500: 0.0,
}

BASE_TAKE_EDGE: Dict[str, float] = {
    "HYDROGEL_PACK": 6, "VELVETFRUIT_EXTRACT": 2,
    "VEV_4000": 6, "VEV_4500": 5, "VEV_5000": 2, "VEV_5100": 2,
    "VEV_5200": 1, "VEV_5300": 1, "VEV_5400": 1, "VEV_5500": 1,
    "VEV_6000": 999, "VEV_6500": 999,
}
BASE_MAKE_EDGE: Dict[str, float] = {
    "HYDROGEL_PACK": 4, "VELVETFRUIT_EXTRACT": 1.5,
    "VEV_4000": 4, "VEV_4500": 3, "VEV_5000": 1.5, "VEV_5100": 1.5,
    "VEV_5200": 1, "VEV_5300": 1, "VEV_5400": 1, "VEV_5500": 1,
    "VEV_6000": 999, "VEV_6500": 999,
}

FOLLOW: Dict[str, set] = {
    "HYDROGEL_PACK": {"Mark 14"},
    "VEV_4000": {"Mark 14"},
    "VELVETFRUIT_EXTRACT": {"Mark 01", "Mark 67"},
}
FADE: Dict[str, set] = {
    "HYDROGEL_PACK": {"Mark 38"},
    "VEV_4000": {"Mark 38"},
    "VELVETFRUIT_EXTRACT": {"Mark 55", "Mark 49"},
}

# Tunables.
FLOW_DECAY = 0.92
FLOW_UNIT = 0.05
FLOW_PRICE_WEIGHT = 0.6
FLOW_STRONG = 2.0  # |flow| above which adverse-selection kicks in

MR_ENTRY_Z = 1.5
MR_PULL = 0.10
MR_CAP_VOL_MULT = 1.0

DELTA_SOFT = 25.0
DELTA_HARD = 40.0
DELTA_SKEW_STRENGTH = 0.08
VELVET_HEDGE_PRESSURE_STRENGTH = 1.25

ALPHA_EMA = 2.0 / (60.0 + 1.0)
ALPHA_SLOW = 1.0 - 0.5 ** (1.0 / 350.0)   # half-life ~350
ALPHA_VOL = 2.0 / (100.0 + 1.0)
ALPHA_RESID = 2.0 / (300.0 + 1.0)         # residual z EWMA span ~300

# Per-strike TV alpha (slower at high-gamma 5200/5300).
TV_ALPHA: Dict[int, float] = {K: 0.03 for K in STRIKES}
TV_ALPHA[5200] = 0.015
TV_ALPHA[5300] = 0.015

# Residual z thresholds and tilt strength.
RESID_Z_THRESHOLD = 1.25
RESID_Z_TILT = 0.30  # how strongly z shifts expected (× vol)

# Dynamic edge multipliers.
EDGE_VOL_MULT = 0.20
EDGE_SPREAD_MULT = 0.25
MAKE_EDGE_VOL_MULT = 0.15

# Adverse-selection threshold.
ADV_RETURN_VOL_MULT = 1.5

# Microprice tilt and inventory skew strength.
MICRO_TILT = 0.30
INV_SKEW_K = 1.2

# Warmup.
WARMUP_TICKS = 60

# Endgame.
ENDGAME_START = 990_000

# TV-quality spread cap multiplier (× base_make_edge, with a floor of 6).
TV_SPREAD_FLOOR = 6.0
TV_SPREAD_MULT = 4.0


# =========================================================================== #
# Helpers                                                                      #
# =========================================================================== #

def safe_json_loads(s: str) -> dict:
    if not s:
        return {}
    try:
        out = json.loads(s)
        return out if isinstance(out, dict) else {}
    except (ValueError, TypeError):
        return {}


def clamp(x: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, x))


def best_bid_ask(order_depth: OrderDepth) -> Tuple[Optional[int], Optional[int]]:
    bb = max(order_depth.buy_orders) if order_depth.buy_orders else None
    ba = min(order_depth.sell_orders) if order_depth.sell_orders else None
    return bb, ba


def mid_price(order_depth: OrderDepth) -> Optional[float]:
    bb, ba = best_bid_ask(order_depth)
    if bb is None or ba is None:
        return None
    return (bb + ba) / 2.0


def microprice(order_depth: OrderDepth) -> Optional[float]:
    bb, ba = best_bid_ask(order_depth)
    if bb is None and ba is None:
        return None
    if bb is None:
        return float(ba)
    if ba is None:
        return float(bb)
    bsz = abs(order_depth.buy_orders[bb])
    asz = abs(order_depth.sell_orders[ba])
    tot = bsz + asz
    if tot <= 0:
        return (bb + ba) / 2.0
    return (asz * bb + bsz * ba) / tot


def update_ewma(prev: Optional[float], x: float, alpha: float) -> float:
    if prev is None:
        return x
    return (1.0 - alpha) * float(prev) + alpha * x


# --- Reservation tracker --------------------------------------------------- #

class Book:
    """Per-product remaining capacity, accounting for orders queued this tick."""
    __slots__ = ("product", "position", "limit", "buy_used", "sell_used")

    def __init__(self, product: str, position: int) -> None:
        self.product = product
        self.position = position
        self.limit = LIMITS.get(product, 20)
        self.buy_used = 0
        self.sell_used = 0

    def buy_room(self) -> int:
        return max(0, self.limit - self.position - self.buy_used)

    def sell_room(self) -> int:
        return max(0, self.limit + self.position - self.sell_used)

    def effective_position(self) -> int:
        """Net position if all queued orders fill."""
        return self.position + self.buy_used - self.sell_used


def add_order_safely(
    orders: List[Order],
    book: Book,
    price: int,
    qty: int,
) -> bool:
    """Append an order if size > 0 and within remaining capacity. Updates book."""
    if qty == 0:
        return False
    if qty > 0:
        q = min(qty, book.buy_room())
        if q <= 0:
            return False
        orders.append(Order(book.product, int(price), int(q)))
        book.buy_used += q
        return True
    q = min(-qty, book.sell_room())
    if q <= 0:
        return False
    orders.append(Order(book.product, int(price), -int(q)))
    book.sell_used += q
    return True


# --- Memory ---------------------------------------------------------------- #

def ensure_product_state(memory: dict, product: str) -> dict:
    products = memory.setdefault("products", {})
    p = products.get(product)
    if not isinstance(p, dict):
        p = {}
        products[product] = p
    return p


def ensure_tv(memory: dict) -> Dict[str, float]:
    tv = memory.get("tv")
    if not isinstance(tv, dict):
        tv = {}
        memory["tv"] = tv
    for K, seed in TV_SEED.items():
        tv.setdefault(str(K), seed)
    return tv


def ensure_stats(memory: dict) -> Dict[str, int]:
    s = memory.get("stats")
    if not isinstance(s, dict):
        s = {
            "take_buys": 0, "take_sells": 0,
            "maker_bids": 0, "maker_asks": 0,
            "skipped_delta": 0, "skipped_no_edge": 0,
            "skipped_adverse": 0,
        }
        memory["stats"] = s
    return s


def update_product_memory(pstate: dict, mid: float) -> Tuple[float, float, float, float, float, int]:
    """Update EMA, slow_mean/var, vol, last_return, ticks. Returns key metrics."""
    ema = update_ewma(pstate.get("ema"), mid, ALPHA_EMA)
    slow_mean = update_ewma(pstate.get("slow_mean"), mid, ALPHA_SLOW)
    prev_var = float(pstate.get("slow_var", 1.0))
    resid = mid - slow_mean
    slow_var = max((1.0 - ALPHA_SLOW) * prev_var + ALPHA_SLOW * resid * resid, 1.0)

    prev_mid = pstate.get("prev_mid")
    prev_vol = float(pstate.get("vol", 1.0))
    if prev_mid is None:
        last_return = 0.0
        new_vol = max(prev_vol, 0.5)
    else:
        last_return = mid - float(prev_mid)
        new_vol = update_ewma(prev_vol, abs(last_return), ALPHA_VOL)

    ticks = int(pstate.get("ticks", 0)) + 1
    pstate["ema"] = ema
    pstate["slow_mean"] = slow_mean
    pstate["slow_var"] = slow_var
    pstate["vol"] = max(new_vol, 0.5)
    pstate["prev_mid"] = mid
    pstate["last_return"] = last_return
    pstate["ticks"] = ticks
    return ema, slow_mean, slow_var, max(new_vol, 0.5), last_return, ticks


def update_residual_z(pstate: dict, mid: float, fair: float) -> float:
    """EWMA residual mean and variance; returns standardized z."""
    resid = mid - fair
    prev_mean = float(pstate.get("rz_mean", 0.0))
    prev_var = float(pstate.get("rz_var", 1.0))
    delta = resid - prev_mean
    new_mean = prev_mean + ALPHA_RESID * delta
    new_var = max(
        (1.0 - ALPHA_RESID) * (prev_var + ALPHA_RESID * delta * delta),
        0.25,
    )
    pstate["rz_mean"] = new_mean
    pstate["rz_var"] = new_var
    std = new_var ** 0.5
    if std <= 0:
        return 0.0
    return (resid - new_mean) / std


# =========================================================================== #
# S_hat / VEV fairs                                                            #
# =========================================================================== #

def estimate_s_hat(
    mids: Dict[str, float],
    tv: Dict[str, float],
    velvet_vol: float,
    prev_s_hat: Optional[float],
) -> Optional[float]:
    """Two-pass weighted mean with outlier rejection; falls back to VELVET / prev."""
    parts: List[Tuple[float, float]] = []
    velvet = mids.get("VELVETFRUIT_EXTRACT")
    if velvet is not None:
        parts.append((velvet, 4.0))
    if "VEV_4000" in mids:
        parts.append((mids["VEV_4000"] + 4000.0, 2.0))
    if "VEV_4500" in mids:
        parts.append((mids["VEV_4500"] + 4500.0, 2.0))
    if "VEV_5000" in mids:
        parts.append((mids["VEV_5000"] + 5000.0 - float(tv.get("5000", TV_SEED[5000])), 1.0))

    if not parts:
        return velvet if velvet is not None else prev_s_hat

    if SIMPLE_S_HAT:
        s = sum(w * v for v, w in parts)
        w_tot = sum(w for _, w in parts)
        return s / w_tot if w_tot > 0 else (velvet if velvet is not None else prev_s_hat)

    # Pass 1: weighted mean.
    s = sum(w * v for v, w in parts)
    w_tot = sum(w for _, w in parts)
    prelim = s / w_tot if w_tot > 0 else (velvet if velvet is not None else prev_s_hat)
    if prelim is None:
        return prev_s_hat

    # Pass 2: drop outliers > max(8, 2.5 * velvet_vol) from the preliminary mean.
    cutoff = max(8.0, 2.5 * max(float(velvet_vol), 0.5))
    kept = [(v, w) for v, w in parts if abs(v - prelim) <= cutoff]
    if len(kept) < 2:
        return velvet if velvet is not None else prev_s_hat

    s = sum(w * v for v, w in kept)
    w_tot = sum(w for _, w in kept)
    return s / w_tot if w_tot > 0 else prelim


def update_tv(
    tv: Dict[str, float],
    mids: Dict[str, float],
    order_depths: Dict[str, OrderDepth],
    s_hat: Optional[float],
) -> None:
    """Quality-filtered TV update; pin wings; respect TV_BOUNDS."""
    if s_hat is None:
        return
    for K in STRIKES:
        product = VEV_BY_STRIKE[K]
        if product in WINGS:
            tv[str(K)] = 0.5
            continue
        if product not in mids:
            continue
        od = order_depths.get(product)
        if od is None or not od.buy_orders or not od.sell_orders:
            continue
        bb, ba = best_bid_ask(od)
        if bb is None or ba is None:
            continue
        spread = ba - bb
        spread_cap = max(TV_SPREAD_FLOOR, TV_SPREAD_MULT * BASE_MAKE_EDGE.get(product, 1))
        if spread > spread_cap:
            continue

        observed = mids[product] - max(s_hat - K, 0.0)
        lo, hi = TV_BOUNDS[K]
        # Reject ticks far outside generous bounds (likely bad data).
        if not (lo - 5.0 <= observed <= hi + 5.0):
            continue
        observed = clamp(observed, lo, hi)
        alpha = TV_ALPHA.get(K, 0.03)
        tv[str(K)] = update_ewma(tv.get(str(K), TV_SEED[K]), observed, alpha)


def compute_vev_fairs(s_hat: Optional[float], tv: Dict[str, float]) -> Dict[str, float]:
    """Voucher fair = max(S_hat - K, 0) + tv_K, monotone non-increasing by K. Wings = 0.5."""
    if s_hat is None:
        return {p: 0.5 for p in WINGS}
    fairs: Dict[str, float] = {}
    prev: Optional[float] = None
    for K in STRIKES:
        product = VEV_BY_STRIKE[K]
        if product in WINGS:
            fair = 0.5
        else:
            fair = max(float(s_hat) - K, 0.0) + float(tv.get(str(K), TV_SEED[K]))
            if prev is not None:
                fair = min(fair, prev)
        fairs[product] = max(0.5, fair)
        if product not in WINGS:
            prev = fairs[product]
    # Wings are pinned regardless of monotone pass.
    for w in WINGS:
        fairs[w] = 0.5
    return fairs


# =========================================================================== #
# Delta / Flow / MR                                                            #
# =========================================================================== #

def compute_net_delta(position: Dict[str, int]) -> float:
    total = float(position.get("VELVETFRUIT_EXTRACT", 0))
    for K in STRIKES:
        total += float(position.get(VEV_BY_STRIKE[K], 0)) * DELTA.get(K, 0.0)
    return total


def delta_for(product: str) -> float:
    if product == "VELVETFRUIT_EXTRACT":
        return 1.0
    K = PRODUCT_TO_STRIKE.get(product)
    return DELTA.get(K, 0.0) if K is not None else 0.0


def flow_weight(product: str, trader: str) -> float:
    if trader in FOLLOW.get(product, set()):
        return 1.0
    if trader in FADE.get(product, set()):
        return -1.0
    return 0.0


def update_flow(memory: dict, market_trades: Dict[str, List[Trade]]) -> None:
    products = memory.setdefault("products", {})
    for raw in products.values():
        if isinstance(raw, dict):
            raw["flow"] = FLOW_DECAY * float(raw.get("flow", 0.0))
    if not ENABLE_FLOW:
        return
    for product, trades in market_trades.items():
        if product not in FOLLOW and product not in FADE:
            continue
        pstate = ensure_product_state(memory, product)
        signal = float(pstate.get("flow", 0.0))
        for t in trades:
            if not isinstance(t, Trade):
                continue
            qty = max(1, abs(int(t.quantity)))
            buyer_w = flow_weight(product, str(t.buyer))
            seller_w = flow_weight(product, str(t.seller))
            signal += FLOW_UNIT * qty * (buyer_w - seller_w)
        pstate["flow"] = clamp(signal, -8.0, 8.0)


def flow_offset(pstate: dict, vol: float) -> float:
    raw = FLOW_PRICE_WEIGHT * float(pstate.get("flow", 0.0))
    cap = 1.5 * max(vol, 0.5)
    return clamp(raw, -cap, cap)


def mr_offset(product: str, mid: float, pstate: dict, vol: float) -> float:
    if not ENABLE_MR:
        return 0.0
    if product not in {"HYDROGEL_PACK", "VELVETFRUIT_EXTRACT"}:
        return 0.0
    slow = pstate.get("slow_mean")
    var = pstate.get("slow_var")
    if slow is None or var is None:
        return 0.0
    std = max(float(var) ** 0.5, 1.0)
    z = (mid - float(slow)) / std
    if abs(z) < MR_ENTRY_Z:
        return 0.0
    pull = -MR_PULL * (mid - float(slow))
    cap = MR_CAP_VOL_MULT * 2.0 * max(vol, 1.0)
    return clamp(pull, -cap, cap)


# =========================================================================== #
# Dynamic edges                                                                #
# =========================================================================== #

def dynamic_edges(product: str, vol: float, spread: float) -> Tuple[float, float]:
    base_take = float(BASE_TAKE_EDGE.get(product, 2)) * TAKE_EDGE_MULT
    base_make = float(BASE_MAKE_EDGE.get(product, 1)) * MAKE_EDGE_MULT
    if not ENABLE_DYNAMIC_EDGES:
        return base_take, base_make
    take = base_take + EDGE_VOL_MULT * max(vol, 0.0) + EDGE_SPREAD_MULT * max(spread, 0.0)
    make = base_make + MAKE_EDGE_VOL_MULT * max(vol, 0.0)
    return max(take, base_take), max(make, base_make)


# =========================================================================== #
# Trader                                                                       #
# =========================================================================== #

class Trader:

    def run(self, state: TradingState) -> Tuple[Dict[str, List[Order]], int, str]:
        memory = safe_json_loads(state.traderData)
        memory.setdefault("products", {})
        stats = ensure_stats(memory)

        update_flow(memory, state.market_trades or {})
        tv = ensure_tv(memory)

        endgame = ENABLE_ENDGAME and (int(state.timestamp) % 1_000_000) > ENDGAME_START

        mids: Dict[str, float] = {}
        for product, od in state.order_depths.items():
            m = mid_price(od)
            if m is not None:
                mids[product] = m

        velvet_pstate = memory.get("products", {}).get("VELVETFRUIT_EXTRACT") or {}
        velvet_vol = float(velvet_pstate.get("vol", 1.0))
        prev_s_hat = memory.get("s_hat")

        s_hat = estimate_s_hat(mids, tv, velvet_vol, prev_s_hat)
        if s_hat is not None:
            memory["s_hat"] = s_hat
        update_tv(tv, mids, state.order_depths, s_hat)

        vev_fairs = compute_vev_fairs(s_hat, tv) if ENABLE_VEV_LADDER else {p: 0.5 for p in WINGS}

        position_map: Dict[str, int] = state.position or {}
        net_delta = compute_net_delta(position_map) if ENABLE_DELTA_CONTROL else 0.0

        result: Dict[str, List[Order]] = {}
        for product, od in state.order_depths.items():
            if ACTIVE_PRODUCTS is not None and product not in ACTIVE_PRODUCTS:
                result[product] = []
                continue
            position = int(position_map.get(product, 0))
            pstate = ensure_product_state(memory, product)
            book = Book(product, position)
            if product in WINGS:
                orders = self.trade_wing(product, od, book, endgame)
            else:
                orders = self.trade_one(
                    product=product,
                    od=od,
                    pstate=pstate,
                    book=book,
                    s_hat=s_hat,
                    vev_fairs=vev_fairs,
                    net_delta=net_delta,
                    endgame=endgame,
                    stats=stats,
                )
            result[product] = orders

        # Cap diagnostic counters so traderData never balloons.
        for k, v in list(stats.items()):
            if isinstance(v, int) and v > 1_000_000_000:
                stats[k] = 1_000_000_000

        return result, 0, json.dumps(memory, separators=(",", ":"))

    # ---- per-product main path ------------------------------------------- #

    def trade_one(
        self,
        product: str,
        od: OrderDepth,
        pstate: dict,
        book: Book,
        s_hat: Optional[float],
        vev_fairs: Dict[str, float],
        net_delta: float,
        endgame: bool,
        stats: Dict[str, int],
    ) -> List[Order]:
        orders: List[Order] = []
        bb, ba = best_bid_ask(od)
        if bb is None or ba is None:
            return orders
        mid = (bb + ba) / 2.0
        spread = ba - bb

        ema, slow_mean, slow_var, vol, last_return, ticks = update_product_memory(pstate, mid)

        # Base fair per family.
        if product == "HYDROGEL_PACK":
            base = ema
        elif product == "VELVETFRUIT_EXTRACT":
            base = float(s_hat) if s_hat is not None else ema
        else:
            base = vev_fairs.get(product, ema)

        # Residual z update — kept warm even during warmup.
        rz = 0.0
        is_vev_non_wing = product.startswith("VEV_") and product not in WINGS
        if is_vev_non_wing:
            rz = update_residual_z(pstate, mid, base)

        if ticks < WARMUP_TICKS:
            return orders

        position = book.position
        limit = book.limit

        # ---- Offsets ----------------------------------------------------- #
        micro = microprice(od) or mid
        micro_offset = MICRO_TILT * (micro - base)

        flow_off = flow_offset(pstate, vol) if ENABLE_FLOW else 0.0
        mr_off = mr_offset(product, mid, pstate, vol)

        inv_skew = INV_SKEW_K * (position / max(1.0, float(limit))) * max(vol, 1.0)

        my_delta = delta_for(product)
        delta_skew = 0.0
        if ENABLE_DELTA_CONTROL:
            delta_skew = DELTA_SKEW_STRENGTH * net_delta * my_delta

        velvet_hedge = 0.0
        if ENABLE_VELVET_HEDGE_PRESSURE and product == "VELVETFRUIT_EXTRACT":
            hp = clamp(net_delta / DELTA_HARD, -1.5, 1.5)
            raw = VELVET_HEDGE_PRESSURE_STRENGTH * hp * max(vol, 1.0)
            velvet_hedge = clamp(raw, -2.0 * max(vol, 1.0), 2.0 * max(vol, 1.0))

        z_tilt = 0.0
        if ENABLE_RESIDUAL_Z and is_vev_non_wing:
            z_tilt = RESID_Z_TILT * rz * max(vol, 0.5)

        expected = (
            base + micro_offset + mr_off + flow_off
            - inv_skew - delta_skew - velvet_hedge - z_tilt
        )

        # ---- Edges ------------------------------------------------------- #
        take_edge, make_edge = dynamic_edges(product, vol, spread)
        if endgame:
            take_edge *= 1.5
            make_edge *= 1.25

        # ---- Gates ------------------------------------------------------- #
        delta_block_buy = ENABLE_DELTA_CONTROL and (
            (net_delta > DELTA_HARD and my_delta > 0)
            or (net_delta < -DELTA_HARD and my_delta < 0)
        )
        delta_block_sell = ENABLE_DELTA_CONTROL and (
            (net_delta < -DELTA_HARD and my_delta > 0)
            or (net_delta > DELTA_HARD and my_delta < 0)
        )
        eg_block_buy = endgame and position >= 0
        eg_block_sell = endgame and position <= 0

        # Adverse-selection signals.
        adverse_buy = False
        adverse_sell = False
        if ENABLE_ADVERSE_SELECTION_FILTER:
            if abs(last_return) > ADV_RETURN_VOL_MULT * max(vol, 0.5):
                if last_return > 0:
                    adverse_buy = True
                elif last_return < 0:
                    adverse_sell = True
            flow_v = float(pstate.get("flow", 0.0))
            if flow_v > FLOW_STRONG:
                adverse_sell = True
            elif flow_v < -FLOW_STRONG:
                adverse_buy = True

        cheap_protect = ENABLE_CHEAP_VEV_RULE and product in CHEAP_VEVS_NON_WING
        cheap_fair = vev_fairs.get(product, base)

        # ---- Takers ------------------------------------------------------ #
        if ENABLE_TAKER and not (delta_block_buy or eg_block_buy):
            for ap in sorted(od.sell_orders):
                if book.buy_room() <= 0:
                    break
                eff_pos = book.effective_position()
                # Aggressive cheap-VEV buyback when short.
                allow_aggressive_buy = (
                    cheap_protect and eff_pos < 0 and ap <= cheap_fair + 1
                )
                if ap > expected - take_edge and not allow_aggressive_buy:
                    break

                # Edge strength → size cap (tighter for near-ATM).
                excess = (expected - take_edge) - ap
                if product in NEAR_ATM:
                    if excess >= take_edge:
                        max_size = 3
                    elif excess >= 0.5 * take_edge:
                        max_size = 2
                    else:
                        max_size = 1
                else:
                    max_size = limit
                if allow_aggressive_buy:
                    max_size = limit

                avail = abs(od.sell_orders[ap])
                q = min(avail, book.buy_room(), max_size)
                if q > 0 and add_order_safely(orders, book, ap, q):
                    stats["take_buys"] = stats.get("take_buys", 0) + 1

        if ENABLE_TAKER and not (delta_block_sell or eg_block_sell):
            for bp in sorted(od.buy_orders, reverse=True):
                if book.sell_room() <= 0:
                    break
                if bp < expected + take_edge:
                    break

                eff_pos = book.effective_position()
                if cheap_protect and eff_pos <= 0:
                    # Hard cheap-VEV short rule: bid >= fair + max(2, 1.5*take_edge)
                    # AND voucher must look genuinely overpriced (rz > threshold).
                    short_threshold = cheap_fair + max(2.0, CHEAP_SHORT_THRESHOLD_MULT * take_edge)
                    if bp < short_threshold:
                        break
                    if ENABLE_RESIDUAL_Z and rz < RESID_Z_THRESHOLD:
                        break

                # Allow aggressive cheap-VEV unwind when long.
                allow_aggressive_sell = (
                    cheap_protect and eff_pos > 0 and bp >= cheap_fair + 1
                )

                excess = bp - (expected + take_edge)
                if product in NEAR_ATM:
                    if excess >= take_edge:
                        max_size = 3
                    elif excess >= 0.5 * take_edge:
                        max_size = 2
                    else:
                        max_size = 1
                else:
                    max_size = limit
                if allow_aggressive_sell:
                    max_size = limit

                avail = abs(od.buy_orders[bp])
                q = min(avail, book.sell_room(), max_size)
                if q > 0 and add_order_safely(orders, book, bp, -q):
                    stats["take_sells"] = stats.get("take_sells", 0) + 1

        # ---- Makers ------------------------------------------------------ #
        if not ENABLE_MAKER:
            return orders

        # Inventory-driven price skew (drag quotes toward reducing inventory).
        skew = -INV_SKEW_K * (position / max(1.0, float(limit))) * make_edge
        skew = clamp(skew, -1.35 * make_edge, 1.35 * make_edge)

        max_bid = expected + skew - make_edge   # highest price we'd bid
        min_ask = expected + skew + make_edge   # lowest price we'd ask

        # Improve by one tick only if doing so still meets edge; else join; else skip.
        cand_b = bb + 1
        if cand_b <= max_bid:
            mb: Optional[int] = cand_b
        elif bb <= max_bid:
            mb = bb
        else:
            mb = None

        cand_a = ba - 1
        if cand_a >= min_ask:
            ma: Optional[int] = cand_a
        elif ba >= min_ask:
            ma = ba
        else:
            ma = None

        # Never crossed.
        if mb is not None and mb >= ba:
            mb = None
        if ma is not None and ma <= bb:
            ma = None
        if mb is not None and ma is not None and mb >= ma:
            mb, ma = None, None

        # Inventory-aware maker size.
        if product in {"HYDROGEL_PACK", "VELVETFRUIT_EXTRACT"}:
            base_ms = 4
        elif product in NEAR_ATM:
            base_ms = 2
        else:
            base_ms = 1

        ms_buy = base_ms
        ms_sell = base_ms
        # Slightly larger when reducing inventory.
        if position > 0:
            ms_sell = base_ms + 1
        if position < 0:
            ms_buy = base_ms + 1
        # Smaller when near limit.
        room_b = book.buy_room()
        room_s = book.sell_room()
        if room_b > 0 and room_b <= base_ms:
            ms_buy = max(1, room_b)
        elif room_b == 0:
            ms_buy = 0
        if room_s > 0 and room_s <= base_ms:
            ms_sell = max(1, room_s)
        elif room_s == 0:
            ms_sell = 0

        # Adverse-selection: shrink or skip on the adverse side.
        if adverse_buy:
            ms_buy = max(0, ms_buy - 2)
        if adverse_sell:
            ms_sell = max(0, ms_sell - 2)

        # Cheap-VEV: never open shorts via maker.
        cheap_no_maker_short = (
            ENABLE_CHEAP_VEV_RULE
            and product in CHEAP_VEVS_NON_WING
            and book.effective_position() <= 0
        )

        if mb is not None and ms_buy > 0 and not (delta_block_buy or eg_block_buy):
            if add_order_safely(orders, book, mb, ms_buy):
                stats["maker_bids"] = stats.get("maker_bids", 0) + 1

        if (
            ma is not None and ms_sell > 0
            and not (delta_block_sell or eg_block_sell)
            and not cheap_no_maker_short
        ):
            if add_order_safely(orders, book, ma, -ms_sell):
                stats["maker_asks"] = stats.get("maker_asks", 0) + 1

        # ---- Diagnostics ------------------------------------------------- #
        if delta_block_buy or delta_block_sell:
            stats["skipped_delta"] = stats.get("skipped_delta", 0) + 1
        if mb is None and ma is None:
            stats["skipped_no_edge"] = stats.get("skipped_no_edge", 0) + 1
        if adverse_buy or adverse_sell:
            stats["skipped_adverse"] = stats.get("skipped_adverse", 0) + 1

        return orders

    # ---- floor wing handler --------------------------------------------- #

    def trade_wing(
        self,
        product: str,
        od: OrderDepth,
        book: Book,
        endgame: bool,
    ) -> List[Order]:
        """VEV_6000 / VEV_6500: fair = 0.5. Bid 0 only; ask 1 only if long."""
        orders: List[Order] = []
        bb, ba = best_bid_ask(od)

        # Scoop a 0-priced ask if any seller appears at price 0 (rare, free PnL).
        if not endgame and ba is not None and ba <= 0:
            avail = abs(od.sell_orders[ba])
            q = min(3, avail, book.buy_room())
            if q > 0:
                add_order_safely(orders, book, ba, q)

        # Resting maker bid at 0.
        if not endgame:
            add_order_safely(orders, book, 0, 2)

        # Ask 1 only to unwind longs.
        if book.position > 0:
            unwind = min(book.position, 8 if endgame else 4)
            add_order_safely(orders, book, 1, -unwind)

        return orders
